/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lunas.dailydo.view;

/**
 *
 * @author Diego Bloise
 */
public class mainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public mainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        headerPane = new javax.swing.JPanel();
        headerTitleLabel = new javax.swing.JLabel();
        headerSubtitleLabel = new javax.swing.JLabel();
        addProjectPane = new javax.swing.JPanel();
        addProjectLabel = new javax.swing.JLabel();
        addProjectIconLabel = new javax.swing.JLabel();
        addTaskPane = new javax.swing.JPanel();
        addTaskLabel = new javax.swing.JLabel();
        addTaskIconLabel = new javax.swing.JLabel();
        projectsPane = new javax.swing.JPanel();
        projectsPaneScroll = new javax.swing.JScrollPane();
        projectsPaneList = new javax.swing.JList<>();
        tasksPane = new javax.swing.JPanel();
        noTasksPane = new javax.swing.JPanel();
        noTasksIconLabel = new javax.swing.JLabel();
        noTasksTitleLabel = new javax.swing.JLabel();
        noTasksSubtitleLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DailyDo");
        setMinimumSize(new java.awt.Dimension(600, 700));

        headerPane.setBackground(new java.awt.Color(107, 0, 204));
        headerPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        headerTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        headerTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerTitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        headerTitleLabel.setText(" DailyDo");

        headerSubtitleLabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        headerSubtitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerSubtitleLabel.setText("Do everything on time, stress-free");

        javax.swing.GroupLayout headerPaneLayout = new javax.swing.GroupLayout(headerPane);
        headerPane.setLayout(headerPaneLayout);
        headerPaneLayout.setHorizontalGroup(
            headerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPaneLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(headerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerTitleLabel)
                    .addComponent(headerSubtitleLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPaneLayout.setVerticalGroup(
            headerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPaneLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(headerTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerSubtitleLabel)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        addProjectPane.setBackground(new java.awt.Color(255, 255, 255));
        addProjectPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        addProjectLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addProjectLabel.setForeground(new java.awt.Color(107, 0, 204));
        addProjectLabel.setText("Projects");

        addProjectIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addProjectIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-purple.png"))); // NOI18N

        javax.swing.GroupLayout addProjectPaneLayout = new javax.swing.GroupLayout(addProjectPane);
        addProjectPane.setLayout(addProjectPaneLayout);
        addProjectPaneLayout.setHorizontalGroup(
            addProjectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProjectPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addProjectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addProjectIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        addProjectPaneLayout.setVerticalGroup(
            addProjectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProjectPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addProjectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addProjectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addProjectIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap())
        );

        addTaskPane.setBackground(new java.awt.Color(255, 255, 255));
        addTaskPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        addTaskLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addTaskLabel.setForeground(new java.awt.Color(107, 0, 204));
        addTaskLabel.setText("Tasks");

        addTaskIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addTaskIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-purple.png"))); // NOI18N

        javax.swing.GroupLayout addTaskPaneLayout = new javax.swing.GroupLayout(addTaskPane);
        addTaskPane.setLayout(addTaskPaneLayout);
        addTaskPaneLayout.setHorizontalGroup(
            addTaskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTaskPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addTaskLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTaskIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        addTaskPaneLayout.setVerticalGroup(
            addTaskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addTaskPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addTaskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addTaskIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addTaskLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        projectsPane.setBackground(new java.awt.Color(255, 255, 255));
        projectsPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        projectsPaneList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        projectsPaneList.setForeground(new java.awt.Color(107, 0, 204));
        projectsPaneList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        projectsPaneList.setFixedCellHeight(50);
        projectsPaneScroll.setViewportView(projectsPaneList);

        javax.swing.GroupLayout projectsPaneLayout = new javax.swing.GroupLayout(projectsPane);
        projectsPane.setLayout(projectsPaneLayout);
        projectsPaneLayout.setHorizontalGroup(
            projectsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projectsPaneScroll)
                .addContainerGap())
        );
        projectsPaneLayout.setVerticalGroup(
            projectsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projectsPaneScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addContainerGap())
        );

        tasksPane.setBackground(new java.awt.Color(255, 255, 255));
        tasksPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        noTasksPane.setBackground(new java.awt.Color(255, 255, 255));

        noTasksIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noTasksIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check-purple.png"))); // NOI18N

        noTasksTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        noTasksTitleLabel.setForeground(new java.awt.Color(107, 0, 204));
        noTasksTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noTasksTitleLabel.setText("There are no tasks here!");

        noTasksSubtitleLabel.setForeground(new java.awt.Color(102, 102, 102));
        noTasksSubtitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noTasksSubtitleLabel.setText("Click in the add button to add a new task");

        javax.swing.GroupLayout noTasksPaneLayout = new javax.swing.GroupLayout(noTasksPane);
        noTasksPane.setLayout(noTasksPaneLayout);
        noTasksPaneLayout.setHorizontalGroup(
            noTasksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(noTasksIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(noTasksTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(noTasksSubtitleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        noTasksPaneLayout.setVerticalGroup(
            noTasksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noTasksPaneLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(noTasksIconLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTasksTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTasksSubtitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tasksPaneLayout = new javax.swing.GroupLayout(tasksPane);
        tasksPane.setLayout(tasksPaneLayout);
        tasksPaneLayout.setHorizontalGroup(
            tasksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tasksPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noTasksPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tasksPaneLayout.setVerticalGroup(
            tasksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tasksPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noTasksPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addProjectPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(projectsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tasksPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addTaskPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addProjectPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addTaskPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tasksPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(projectsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new mainScreen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addProjectIconLabel;
    private javax.swing.JLabel addProjectLabel;
    private javax.swing.JPanel addProjectPane;
    private javax.swing.JLabel addTaskIconLabel;
    private javax.swing.JLabel addTaskLabel;
    private javax.swing.JPanel addTaskPane;
    private javax.swing.JPanel headerPane;
    private javax.swing.JLabel headerSubtitleLabel;
    private javax.swing.JLabel headerTitleLabel;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel noTasksIconLabel;
    private javax.swing.JPanel noTasksPane;
    private javax.swing.JLabel noTasksSubtitleLabel;
    private javax.swing.JLabel noTasksTitleLabel;
    private javax.swing.JPanel projectsPane;
    private javax.swing.JList<String> projectsPaneList;
    private javax.swing.JScrollPane projectsPaneScroll;
    private javax.swing.JPanel tasksPane;
    // End of variables declaration//GEN-END:variables
}
